name: Build TWRP for j7xlte

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl python3 zip unzip bc bison build-essential \
            gcc-multilib g++-multilib libxml2-utils zlib1g-dev libc6-dev-i386 \
            libncurses5 libncurses5-dev lib32z1-dev liblz4-tool libssl-dev \
            libtinfo5 libtinfo-dev libstdc++6 nano lzop pngcrush rsync schedtool \
            squashfs-tools repo ca-certificates ccache openjdk-8-jdk

      - name: Set up Repo
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Clone Device Tree
        run: |
          cd ~/twrp/device
          mkdir -p samsung && cd samsung
          git clone https://github.com/twrpdtgen/android_device_samsung_j7xlte j7xlte

      - name: Clone Dependencies
        run: |
          cd ~/twrp
          git clone https://github.com/TeamWin/android_vendor_twrp.git vendor/twrp

      - name: Start Build
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_j7xlte-eng
          make -j$(nproc) recoveryimage

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v3
        with:
          name: twrp-j7xlte
          path: ~/twrp/out/target/product/j7xlte/recovery.img
          
